//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolunteerServices
    {
        public int IdVolunteerService { get; set; }
        public string IdVolunteer { get; set; }
        public string IdService { get; set; }
        public Nullable<int> MonthlyHours { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual Volunteers Volunteers { get; set; }
    }
}
